#!/usr/bin/env bash

docker info >/dev/null 2>&1

if [ ! "$?" == "0" ]; then
    echo "'docker info' failed.  Is docker installed correctly?"
    if [ ! "$UID" == "0" ];then
        echo "You might what to retry as root??"
    fi
    exit 1
fi
export DOCKER_NAME=rds_slow_query_log_examiner
export REPO_NAME=daxchegg
